here are some more errors.  keep focus on each error at atime. so this w

diff --git a/android/gradlew b/android/gradlew
--- a/android/gradlew
+++ b/android/gradlew
@@ -35,7 +35,6 @@ while [ -h "$PRG" ] ; do
         PRG=`dirname "$PRG"`"/$link"
     fi
 done
-
 SAVED="`pwd`"
 cd "`dirname \"$PRG\"`/" >/dev/null
 APP_HOME="`pwd -P`"
@@ -45,35 +44,71 @@ APP_NAME="Gradle"
 APP_BASE_NAME=`basename "$0"`
 
 # Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
-DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
+DEFAULT_JVM_OPTS=""
 
 # Use the maximum available, or set MAX_FD != -1 to use that value.
 MAX_FD="maximum"
 
+warn () {
+    echo "$*"
+}
+
+die () {
+    echo
+    echo "$*"
+    echo
+    exit 1
+}
+
+# OS specific support (must be 'true' or 'false').
+cygwin=false
+msys=false
+darwin=false
+nonstop=false
+case "`uname`" in
+  CYGWIN* )
+    cygwin=true
+    ;;
+  Darwin* )
+    darwin=true
+    ;;
+  MSYS* | MINGW* )
+    msys=true
+    ;;
+  NONSTOP* )
+    nonstop=true
+    ;;
+esac
+
 # For Cygwin, ensure paths are in UNIX format before anything is touched.
-if ${cygwin} ; then
+if $cygwin ; then
     [ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
-    [ -n "$GRADLE_HOME" ] && GRADLE_HOME=`cygpath --unix "$GRADLE_HOME"`
 fi
 
-# Attempt to locate JAVA_HOME if not set.
+# Attempt to find JAVA_HOME if not already set.
 if [ -z "$JAVA_HOME" ] ; then
-    # Cross-platform way to get path to `java`
-    java_exe=`which java 2>/dev/null`
-    if [ -n "$java_exe" ] ; then
-        # Read location of java executable
-        java_exe=`readlink -f "$java_exe"`
-        # Set JAVA_HOME based on path to java executable
-        JAVA_HOME=`dirname "$java_exe"`
-        JAVA_HOME=`(cd "$JAVA_HOME/.." && pwd)`
+    if $darwin ; then
+        if [ -x '/usr/libexec/java_home' ] ; then
+            JAVA_HOME=`/usr/libexec/java_home`
+        elif [ -d "/System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Home" ] ; then
+            JAVA_HOME="/System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Home"
+        fi
+    else
+        javaPathTovisit="/usr/java/packages/lib/amd64 /usr/lib/jvm/java /usr/lib/jvm /usr/lib/java"
+        for jvmdir in $javaPathTovisit; do
+            if [ -x "$jvmdir/bin/java" ]; then
+                JAVA_HOME="$jvmdir"
+                break
+            fi
+        done
     fi
 fi
+
 if [ -z "$JAVA_HOME" ] ; then
-    echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
-    echo
-    echo "Please set the JAVA_HOME variable in your environment to match the"
-    echo "location of your Java installation."
-    exit 1
+    die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
+
+Please set the JAVA_HOME variable in your environment to match the
+location of your Java installation."
 fi
 
 # Set JAVA_EXE
@@ -84,117 +119,57 @@ if [ -n "$JAVA_HOME" ] ; then
     else
         JAVA_EXE="$JAVA_HOME/bin/java"
     fi
+else
+    JAVA_EXE="java"
 fi
 
-# No suitable Java found.
 if [ ! -x "$JAVA_EXE" ] ; then
-    echo "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
-    echo
-    echo "Please set the JAVA_HOME variable in your environment to match the"
-    echo "location of your Java installation."
-    exit 1
+    die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME
+
+Please set the JAVA_HOME variable in your environment to match the
+location of your Java installation."
 fi
 
-# Determine the Java version
-if [ -x "$JAVA_EXE" ] ; then
-    # Ignore the error stream, seems to vary between versions of Java
-    # what is outputted.
-    JAVA_VERSION_LINE=`"$JAVA_EXE" -version 2>&1 | grep 'version' | head -n 1`
-    if [ -n "$JAVA_VERSION_LINE" ] ; then
-        # Every implementation except for openj9 seems to have the version number
-        # surrounded by quotes.
-        # So we'll first try to get the version number within the quotes.
-        # This will fail for openj9.
-        # openj9 version line looks like:
-        #   openjdk version "11.0.12" 2021-07-20
-        #   OpenJDK Runtime Environment AdoptOpenJDK-11.0.12+7 (build 11.0.12+7)
-        #   Eclipse OpenJ9 VM AdoptOpenJDK-11.0.12+7 (build openj9-0.27.0, JRE 11 Mac OS X amd64-64-Bit Compressed References 20210721_950 (JIT enabled, AOT enabled)
-        #   OpenJ9   - 7687a4755
-        #   OMR      - 2b9315694
-        #   JCL      - 649666f91d based on jdk-11.0.12+7)
-        JAVA_VERSION=`echo "$JAVA_VERSION_LINE" | sed -e 's/.*version "\(.*\)"/\1/'`
-        # openj9 version line looks like:
-        #   openjdk version "11.0.12" 2021-07-20
-        # When the version number is not surrounded by quotes, the sed command will
-        # output the whole line.
-        # So we can check if the version number is the same as the whole line.
-        if [ "$JAVA_VERSION" = "$JAVA_VERSION_LINE" ] ; then
-            # We have an openj9 version.
-            # We'll first try to get the version number, which is the 3rd word on the line.
-            JAVA_VERSION=`echo "$JAVA_VERSION_LINE" | awk '{print $3}'`
-            # The version number is surrounded by quotes, so we'll remove them.
-            JAVA_VERSION=`echo "$JAVA_VERSION" | sed -e 's/"//g'`
-        fi
-        # Now we have to massage the version string to get only the major version.
-        # The version string can be in different formats, e.g.:
-        #   "1.8.0_202"
-        #   "11.0.12"
-        #   "17"
-        # So we'll first remove any leading "1." for versions < 9.
-        if echo "$JAVA_VERSION" | grep -e "^1\." > /dev/null ; then
-            JAVA_MAJOR_VERSION=`echo "$JAVA_VERSION" | sed -e 's/1\.\([0-9]*\).*/\1/'`
-        else
-            # For versions > 9, the major version is the first number.
-            JAVA_MAJOR_VERSION=`echo "$JAVA_VERSION" | sed -e 's/\([0-9]*\).*/\1/'`
-        fi
-    else
-        # Fallback to default to 8
-        JAVA_MAJOR_VERSION="8"
-    fi
-fi
-
-# For Darwin, add options to specify how the application appears in the dock
-if [ `uname -s` = "Darwin" ]; then
-    GRADLE_OPTS="$GRADLE_OPTS \"-Xdock:name=$APP_NAME\" \"-Xdock:icon=$APP_HOME/media/gradle.icns\""
+# Set basic GRADLE_OPTS
+# if no java options are set, then set some reasonable defaults
+if [ -z "$JAVA_OPTS" -a -z "$GRADLE_OPTS" ]; then
+    GRADLE_OPTS="-Xmx64m -Xms64m"
 fi
 
 # For Cygwin, switch paths to Windows format before running java
-if ${cygwin} ; then
+if $cygwin ; then
     APP_HOME=`cygpath --path --windows "$APP_HOME"`
     JAVA_HOME=`cygpath --path --windows "$JAVA_HOME"`
     CLASSPATH=`cygpath --path --windows "$CLASSPATH"`
+    CYGHOME=`cygpath --path --windows "$HOME"`
 fi
 
-# Split up the JVM options only if the major version is 9 or higher
-if [ "$JAVA_MAJOR_VERSION" -ge 9 ] ; then
-    JVM_OPTS_ARRAY=(${JVM_OPTS})
-    for jvm_opt in "${JVM_OPTS_ARRAY[@]}"
-    do
-        if [ "$jvm_opt" = "-XX:MaxPermSize=256m" ] ; then
-            # The MaxPermSize flag has been removed in Java 9, and we should not use it anymore.
-            # https://docs.oracle.com/javase/9/tools/java.htm
-            continue
-        elif [[ "$jvm_opt" = --add-opens* ]] ; then
-            # When using Java 9+ and you want to use the reflective access, you have to add these options.
-            # This is a workaround for the fact that the CLI options are not passed to the daemon.
-            # We need to add them to the daemon startup options.
-            # TODO: Find a better way to do this.
-            # Maybe we should pass them to the daemon via the gradle-launcher.
-            # See https://github.com/gradle/gradle/issues/12345
-            # For now, we'll just add them to the daemon startup options.
-            # This is not ideal, but it works.
-            # We'll also add them to the CLI options.
-            # This is so that the CLI can also use the reflective access.
-            ADDITIONAL_OPTS="$ADDITIONAL_OPTS '$jvm_opt'"
-        fi
+# Split up the JVM options only if spaces are available.
+# This allows options such as --add-opens to be passed to the JVM.
+if [ -z "$GRADLE_OPTS_SPACE_OK" ]; then
+    # No spaces in GRADLE_OPTS are allowed.
+    case "$GRADLE_OPTS" in
+        *\ * )
+            die "ERROR: GRADLE_OPTS contains spaces, but the GRADLE_OPTS_SPACE_OK environment variable is not set.
+Please set GRADLE_OPTS_SPACE_OK to 'true' if this is intentional.
+"
+            ;;
+    esac
+fi
+
+# Escape application args
+save () {
+    for i do
+        printf %s\\n "$i" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/'/"
     done
-fi
+    printf \ \\n
+}
+APP_ARGS=`save "$@"`
 
-# Collect all arguments for the java command, following the shell quoting conventions.
-#
-# (Note that we must follow the quoting conventions of the _current_ shell, not
-# necessarily the one that the user is running. For example, if the user is
-# running dash, we must still generate a command that is valid for whatever
-# shell is located at /bin/sh.)
-#
-# We set CLASSPATH here; if we set it as an environment variable, it's
-# length can exceed the maximum command line length.
-eval set -- "$JAVA_EXE" "$DEFAULT_JVM_OPTS" "$JAVA_OPTS" "$GRADLE_OPTS" "$ADDITIONAL_OPTS" -classpath "\"$APP_HOME/gradle/wrapper/gradle-wrapper.jar\"" org.gradle.wrapper.GradleWrapperMain '"$@"'
+# Collect all arguments for the java command, following the shell quoting and substitution rules
+eval set -- "$DEFAULT_JVM_OPTS" $JAVA_OPTS $GRADLE_OPTS "-Dorg.gradle.appname=$APP_BASE_NAME" -classpath \""$APP_HOME/gradle/wrapper/gradle-wrapper.jar"\" org.gradle.wrapper.GradleWrapperMain "$APP_ARGS"
 
-# Execute the command, printing it first.
-# (We're careful to use printf for the command printing, to avoid any issues
-# with echo's parsing of options.)
-printf "Executing command:\n"
-printf "%q " "$@"
-printf "\n\n"
-exec "$@"
+# The following line is for debugging only.
+# echo "Executing command: '$JAVA_EXE' $@"
+
+exec "$JAVA_EXE" "$@"
