i'm hoping we are getting close to fix this issue.  here is another buil

diff --git a/android/gradlew b/android/gradlew
--- a/android/gradlew
+++ b/android/gradlew
@@ -11,7 +11,6 @@
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
-to
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
@@ -21,35 +20,46 @@ to
 DEFAULT_JVM_OPTS=""
 
 APP_NAME="Gradle"
-APP_BASE_NAME=$(basename "$0")
+APP_BASE_NAME=`basename "$0"`
 
 # Use the maximum available, or set MAX_FD != -1 to use that value.
 MAX_FD="maximum"
 
-warn () {
-    echo "$*"
-}
-
-die () {
-    echo
-    echo "ERROR: $*"
-    echo
+# For Darwin, add options to specify how the application appears in the dock
+if [ -z "$JAVA_HOME" ] ; then
+    # If JAVA_HOME is not set, try to determine it.
+    if [ "$(uname -s)" = "Darwin" ] ; then
+        # For macOS, use java_home utility.
+        JAVA_HOME=$(/usr/libexec/java_home)
+    else
+        # For other OSes, use 'which' to find java.
+        JAVA_EXEC=$(which java 2>/dev/null)
+        if [ -n "$JAVA_EXEC" ] ; then
+            # Found java, now getting JAVA_HOME
+            JAVA_HOME=$(dirname "$(dirname "$(readlink -f "$JAVA_EXEC")")")
+        fi
+    fi
+fi
+if [ -z "$JAVA_HOME" ] ; then
+    echo "Error: JAVA_HOME is not set and could not be determined."
     exit 1
-}
+fi
+JAVA_EXEC="$JAVA_HOME/bin/java"
 
-# OS specific support (must be 'true' or 'false').
+
+# OS specific support.  $var _must_ be set to either true or false.
 cygwin=false
 msys=false
 darwin=false
 nonstop=false
-case "$(uname)" in
+case "`uname`" in
   CYGWIN* )
     cygwin=true
     ;;
   Darwin* )
     darwin=true
     ;;
-  MSYS* | MINGW* )
+  MINGW* )
     msys=true
     ;;
   NONSTOP* )
@@ -57,103 +67,115 @@ case "$(uname)" in
     ;;
 esac
 
-# For Cygwin, ensure paths are in UNIX format before anything is touched.
-if ${cygwin} ; then
-    [ -n "$JAVA_HOME" ] && JAVA_HOME=$(cygpath --unix "$JAVA_HOME")
-    [ -n "$GRADLE_HOME" ] && GRADLE_HOME=$(cygpath --unix "$GRADLE_HOME")
-fi
-
 # Attempt to set APP_HOME
 # Resolve links: $0 may be a link
 PRG="$0"
 # Need this for relative symlinks.
 while [ -h "$PRG" ] ; do
-    ls=$(ls -ld "$PRG")
-    link=$(expr "$ls" : '.*-> \(.*\)$')
+    ls=`ls -ld "$PRG"`
+    link=`expr "$ls" : '.*-> \(.*\)$'`
     if expr "$link" : '/.*' > /dev/null; then
         PRG="$link"
     else
-        PRG=$(dirname "$PRG")"/$link"
+        PRG=`dirname "$PRG"`"/$link"
     fi
 done
 
-APP_HOME=$(dirname "$PRG")
+APP_HOME=`dirname "$PRG"`
+
+# Absolutize APP_HOME
+# This is reaching out into the outer reaches of POSIX shell compatibility.
+# You may need to adjust this for your system.
+#
+# N.B. This is not how we resolve paths on Windows (see gradlew.bat)
+#
+# There are many claims to having a fully portable path resolution
+# script. We've tried a few of them, and this is the most robust so far.
+# It's not perfect, but it's "good enough" for the supported platforms.
+# See https://stackoverflow.com/a/246128/1119513
+#
+if [ -z "$APP_HOME" -o ! -d "$APP_HOME" ] ; then
+    echo "Error: Could not determine APP_HOME"
+    exit 1
+fi
+case "$APP_HOME" in
+    /*)
+        # already absolute
+        ;;
+    *)
+        # relative path
+        APP_HOME="$(cd "$APP_HOME" && pwd -P)"
+        ;;
+esac
+
+
+# Add default CATALINA_OPTS here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
+DEFAULT_JVM_OPTS=""
+
+# Use the maximum available, or set MAX_FD != -1 to use that value.
+MAX_FD="maximum"
+
+# For Darwin, add options to specify how the application appears in the dock
+if $darwin; then
+  GRADLE_OPTS="$GRADLE_OPTS \"-Xdock:name=$APP_NAME\" \"-Xdock:icon=$APP_HOME/media/gradle.icns\""
+fi
 
 # For Cygwin, switch paths to Windows format before running java
-if ${cygwin} ; then
-    APP_HOME=$(cygpath --path --windows "$APP_HOME")
-    JAVA_HOME=$(cygpath --path --windows "$JAVA_HOME")
-    GRADLE_HOME=$(cygpath --path --windows "$GRADLE_HOME")
-    CLASSPATH=$(cygpath --path --windows "$CLASSPATH")
-fi
+if $cygwin ; then
+    APP_HOME=`cygpath --path --mixed "$APP_HOME"`
+    CLASSPATH=`cygpath --path --mixed "$CLASSPATH"`
+    JAVACMD=`cygpath --unix "$JAVACMD"`
 
-# Attempt to find Java
-if [ -z "$JAVA_HOME" ] ; then
-    # Macs with JDK 1.6 and above define JAVA_HOME in standard ways
-    if ${darwin} ; then
-        if [ -x '/usr/libexec/java_home' ] ; then
-            JAVA_HOME=$(/usr/libexec/java_home)
-        elif [ -d "/System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Home" ]; then
-            JAVA_HOME="/System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Home"
-        fi
-    fi
-
-    if [ -z "$JAVA_HOME" ]; then
-        # ...less standard Java locations
-        if [ -x "/usr/bin/java" ]; then
-            JAVA_HOME="/usr"
-        fi
-    fi
-
-    if [ -z "$JAVA_HOME" ] ; then
-        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
-
-Please set the JAVA_HOME variable in your environment to match the
-location of your Java installation."
-    fi
-fi
-if [ -z "$JAVACMD" ] ; then
-    if [ -n "$JAVA_HOME"  ] ; then
-        if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
-            # IBM's JDK on AIX uses strange locations for the executables
-            JAVACMD="$JAVA_HOME/jre/sh/java"
-        else
-            JAVACMD="$JAVA_HOME/bin/java"
-        fi
-    else
-        JAVACMD="java"
-    fi
-fi
-if [ ! -x "$JAVACMD" ] ; then
-    die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
-
-Please set the JAVA_HOME variable in your environment to match the
-location of your Java installation."
+    # We build the pattern for arguments to be converted to Windows paths
+    ROOTDIRSRAW=`find -L / -maxdepth 1 -type d -printf '%b\n' | sort | uniq | tr '\n' '|'`
+    ROOTDIRS=`echo $ROOTDIRSRAW | sed 's/.$//'`
+    # The pattern carefully matching arguments starting with a slash but not with a double slash
+    ARG_PATTERN="/((?!/)$ROOTDIRS)(/.*)?"
 fi
 
 # Increase the maximum number of open files
-if ! ${cygwin} && ! ${darwin} && ! ${nonstop} ; then
-    MAX_FD_LIMIT=$(ulimit -H -n)
-    if [ "$?" -eq 0 ] ; then
-        if [ "$MAX_FD" = "maximum" ] || [ "$MAX_FD" = "max" ] ; then
-            # Use the system limit
-            MAX_FD="$MAX_FD_LIMIT"
-        fi
-        ulimit -n "$MAX_FD"
-        if [ "$?" -ne 0 ] ; then
-            warn "Could not set maximum file descriptor limit: $MAX_FD"
+if ! $cygwin && ! $msys; then
+    # Mac OS X and Solaris don't support ulimit -n unlimited
+    if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ]; then
+        # use the system max
+        MAX_FD_LIMIT=`ulimit -H -n`
+        if [ $? -ne 0 ] ; then
+            echo "Could not query system maximum open files. Ignoring."
+        else
+            ulimit -n $MAX_FD_LIMIT
+            if [ $? -ne 0 ] ; then
+                echo "Could not set maximum open files. Ignoring."
+            fi
         fi
     else
-        warn "Could not query maximum file descriptor limit: $MAX_FD_LIMIT"
+        ulimit -n $MAX_FD
+        if [ $? -ne 0 ] ; then
+            echo "Could not set maximum open files. Ignoring."
+        fi
     fi
 fi
 
-# Add the jar to the CLASSPATH and run the wrapper
-exec "$JAVACMD" \
-    "${DEFAULT_JVM_OPTS[@]}" \
-    "${JAVA_OPTS[@]}" \
-    "${GRADLE_OPTS[@]}" \
-    -Dorg.gradle.appname="$APP_BASE_NAME" \
-    -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" \
-    org.gradle.wrapper.GradleWrapperMain \
-    "$@"
+# Collect all arguments for the java command, following the shell quoting rules.
+# This is required to support arguments with spaces.
+# The initialisation of the arguments array is platform-dependent.
+if $darwin ; then
+    # Specific for macOS, which doesn't support the quoting below.
+    # This will not support arguments with spaces.
+    jvm_args_array=$JAVA_OPTS $GRADLE_OPTS
+else
+    # For other OSes, support arguments with spaces.
+    eval "jvm_args_array=($JAVA_OPTS $GRADLE_OPTS)"
+fi
+
+# Prepare the command to run
+# The quoting of the arguments is platform-dependent.
+if $darwin ; then
+    # Specific for macOS, which doesn't support the quoting below.
+    # This will not support arguments with spaces.
+    # Additionally, we must export JAVA_HOME for Gradle to find it.
+    export JAVA_HOME
+    exec "$JAVA_EXEC" "${jvm_args_array[@]}" -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" org.gradle.wrapper.GradleWrapperMain "$@"
+else
+    # For other OSes, support arguments with spaces.
+    exec "$JAVA_EXEC" "${jvm_args_array[@]}" -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" org.gradle.wrapper.GradleWrapperMain "$@"
+fi
