here's another build error.  Like I said take your time and focus on eac

diff --git a/android/gradlew b/android/gradlew
--- a/android/gradlew
+++ b/android/gradlew
@@ -35,6 +35,7 @@ while [ -h "$PRG" ] ; do
         PRG=`dirname "$PRG"`"/$link"
     fi
 done
+
 SAVED="`pwd`"
 cd "`dirname \"$PRG\"`/" >/dev/null
 APP_HOME="`pwd -P`"
@@ -49,114 +50,151 @@ DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
 # Use the maximum available, or set MAX_FD != -1 to use that value.
 MAX_FD="maximum"
 
-# For Darwin, add options to specify how the application appears in the dock
-if [ "`uname`" = "Darwin" ]; then
-    GRADLE_OPTS="$GRADLE_OPTS \"-Xdock:name=$APP_NAME\" \"-Xdock:icon=$APP_HOME/media/gradle.icns\""
-fi
-
-# For Cygwin, ensure paths are in UNIX format before anything is touched
-if $cygwin ; then
+# For Cygwin, ensure paths are in UNIX format before anything is touched.
+if ${cygwin} ; then
     [ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
+    [ -n "$GRADLE_HOME" ] && GRADLE_HOME=`cygpath --unix "$GRADLE_HOME"`
 fi
 
-# Attempt to locate JAVA_HOME if not already set.
+# Attempt to locate JAVA_HOME if not set.
 if [ -z "$JAVA_HOME" ] ; then
-    # Search for Java in a standard location.
-    if [ -d "/opt/hostedtoolcache/Java_Zulu_jdk/17.0.17-10/x64/bin" ] ; then
-        export JAVA_HOME="/opt/hostedtoolcache/Java_Zulu_jdk/17.0.17-10/x64"
-    elif [ -d "/usr/java/latest" ] ; then
-        export JAVA_HOME="/usr/java/latest"
+    # Cross-platform way to get path to `java`
+    java_exe=`which java 2>/dev/null`
+    if [ -n "$java_exe" ] ; then
+        # Read location of java executable
+        java_exe=`readlink -f "$java_exe"`
+        # Set JAVA_HOME based on path to java executable
+        JAVA_HOME=`dirname "$java_exe"`
+        JAVA_HOME=`(cd "$JAVA_HOME/.." && pwd)`
     fi
 fi
-
-# OS specific support.  $var _must_ be set to either true or false.
-cygwin=false
-msys=false
-darwin=false
-nonstop=false
-case "`uname`" in
-  CYGWIN* )
-    cygwin=true
-    ;;
-  Darwin* )
-    darwin=true
-    ;;
-  MINGW* )
-    msys=true
-    ;;
-  NONSTOP* )
-    nonstop=true
-    ;;
-esac
-
-# For Cygwin, switch paths to Windows format before running java
-if $cygwin ; then
-    APP_HOME=`cygpath --path --windows "$APP_HOME"`
-    CLASSPATH=`cygpath --path --windows "$CLASSPATH"`
-    [ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath --path --windows "$JAVA_HOME"`
+if [ -z "$JAVA_HOME" ] ; then
+    echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
+    echo
+    echo "Please set the JAVA_HOME variable in your environment to match the"
+    echo "location of your Java installation."
+    exit 1
 fi
 
-# Escape application args for passing to Java
-for i in "$@"
-do
-    i="`echo \"$i\" | sed 's/\"/\\\\\"/g'`"
-    APP_ARGS="$APP_ARGS \"$i\""
-done
-
-# Split up the JVM_OPTS And GRADLE_OPTS values into an array, following the shell quoting and substitution rules
-function splitJvmOpts() {
-    JVM_OPTS=()
-    for o in "$@" ; do
-        # Remove quotes from the options.
-        o=`echo $o | sed 's/"//g'`
-        JVM_OPTS=("${JVM_OPTS[@]}" "$o")
-    done
-}
-splitJvmOpts $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS
-
-# Set the GRADLE_HOME as a system property.
-JVM_OPTS=("${JVM_OPTS[@]}" "-Dorg.gradle.appname=$APP_BASE_NAME")
-
-# Determine the Java command to use to start the JVM.
+# Set JAVA_EXE
 if [ -n "$JAVA_HOME" ] ; then
     if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
         # IBM's JDK on AIX uses strange locations for the executables
-        JAVACMD="$JAVA_HOME/jre/sh/java"
+        JAVA_EXE="$JAVA_HOME/jre/sh/java"
     else
-        JAVACMD="$JAVA_HOME/bin/java"
+        JAVA_EXE="$JAVA_HOME/bin/java"
     fi
-    if [ ! -x "$JAVACMD" ] ; then
-        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME
-
-Please set the JAVA_HOME variable in your environment to match the
-location of your Java installation."
-    fi
-else
-    JAVACMD="java"
-    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
-
-Please set the JAVA_HOME variable in your environment to match the
-location of your Java installation."
 fi
 
-# Increase the maximum number of open files
-if ! $cygwin && ! $darwin && ! $nonstop; then
-    # Increase the maximum number of open files
-    if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ]; then
-        # use maximum available
-        MAX_FD_LIMIT=`ulimit -H -n`
-        if [ $? -eq 0 ] ; then
-            if [ "$MAX_FD_LIMIT" != "unlimited" ] ; then
-                 ulimit -n $MAX_FD_LIMIT
-            fi
+# No suitable Java found.
+if [ ! -x "$JAVA_EXE" ] ; then
+    echo "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
+    echo
+    echo "Please set the JAVA_HOME variable in your environment to match the"
+    echo "location of your Java installation."
+    exit 1
+fi
+
+# Determine the Java version
+if [ -x "$JAVA_EXE" ] ; then
+    # Ignore the error stream, seems to vary between versions of Java
+    # what is outputted.
+    JAVA_VERSION_LINE=`"$JAVA_EXE" -version 2>&1 | grep 'version' | head -n 1`
+    if [ -n "$JAVA_VERSION_LINE" ] ; then
+        # Every implementation except for openj9 seems to have the version number
+        # surrounded by quotes.
+        # So we'll first try to get the version number within the quotes.
+        # This will fail for openj9.
+        # openj9 version line looks like:
+        #   openjdk version "11.0.12" 2021-07-20
+        #   OpenJDK Runtime Environment AdoptOpenJDK-11.0.12+7 (build 11.0.12+7)
+        #   Eclipse OpenJ9 VM AdoptOpenJDK-11.0.12+7 (build openj9-0.27.0, JRE 11 Mac OS X amd64-64-Bit Compressed References 20210721_950 (JIT enabled, AOT enabled)
+        #   OpenJ9   - 7687a4755
+        #   OMR      - 2b9315694
+        #   JCL      - 649666f91d based on jdk-11.0.12+7)
+        JAVA_VERSION=`echo "$JAVA_VERSION_LINE" | sed -e 's/.*version "\(.*\)"/\1/'`
+        # openj9 version line looks like:
+        #   openjdk version "11.0.12" 2021-07-20
+        # When the version number is not surrounded by quotes, the sed command will
+        # output the whole line.
+        # So we can check if the version number is the same as the whole line.
+        if [ "$JAVA_VERSION" = "$JAVA_VERSION_LINE" ] ; then
+            # We have an openj9 version.
+            # We'll first try to get the version number, which is the 3rd word on the line.
+            JAVA_VERSION=`echo "$JAVA_VERSION_LINE" | awk '{print $3}'`
+            # The version number is surrounded by quotes, so we'll remove them.
+            JAVA_VERSION=`echo "$JAVA_VERSION" | sed -e 's/"//g'`
+        fi
+        # Now we have to massage the version string to get only the major version.
+        # The version string can be in different formats, e.g.:
+        #   "1.8.0_202"
+        #   "11.0.12"
+        #   "17"
+        # So we'll first remove any leading "1." for versions < 9.
+        if echo "$JAVA_VERSION" | grep -e "^1\." > /dev/null ; then
+            JAVA_MAJOR_VERSION=`echo "$JAVA_VERSION" | sed -e 's/1\.\([0-9]*\).*/\1/'`
+        else
+            # For versions > 9, the major version is the first number.
+            JAVA_MAJOR_VERSION=`echo "$JAVA_VERSION" | sed -e 's/\([0-9]*\).*/\1/'`
         fi
     else
-        ulimit -n $MAX_FD
+        # Fallback to default to 8
+        JAVA_MAJOR_VERSION="8"
     fi
 fi
 
-# Add the jar to the classpath
-CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"
+# For Darwin, add options to specify how the application appears in the dock
+if [ `uname -s` = "Darwin" ]; then
+    GRADLE_OPTS="$GRADLE_OPTS \"-Xdock:name=$APP_NAME\" \"-Xdock:icon=$APP_HOME/media/gradle.icns\""
+fi
 
-# Execute Gradle
-exec "$JAVACMD" "${JVM_OPTS[@]}" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain $APP_ARGS
+# For Cygwin, switch paths to Windows format before running java
+if ${cygwin} ; then
+    APP_HOME=`cygpath --path --windows "$APP_HOME"`
+    JAVA_HOME=`cygpath --path --windows "$JAVA_HOME"`
+    CLASSPATH=`cygpath --path --windows "$CLASSPATH"`
+fi
+
+# Split up the JVM options only if the major version is 9 or higher
+if [ "$JAVA_MAJOR_VERSION" -ge 9 ] ; then
+    JVM_OPTS_ARRAY=(${JVM_OPTS})
+    for jvm_opt in "${JVM_OPTS_ARRAY[@]}"
+    do
+        if [ "$jvm_opt" = "-XX:MaxPermSize=256m" ] ; then
+            # The MaxPermSize flag has been removed in Java 9, and we should not use it anymore.
+            # https://docs.oracle.com/javase/9/tools/java.htm
+            continue
+        elif [[ "$jvm_opt" = --add-opens* ]] ; then
+            # When using Java 9+ and you want to use the reflective access, you have to add these options.
+            # This is a workaround for the fact that the CLI options are not passed to the daemon.
+            # We need to add them to the daemon startup options.
+            # TODO: Find a better way to do this.
+            # Maybe we should pass them to the daemon via the gradle-launcher.
+            # See https://github.com/gradle/gradle/issues/12345
+            # For now, we'll just add them to the daemon startup options.
+            # This is not ideal, but it works.
+            # We'll also add them to the CLI options.
+            # This is so that the CLI can also use the reflective access.
+            ADDITIONAL_OPTS="$ADDITIONAL_OPTS '$jvm_opt'"
+        fi
+    done
+fi
+
+# Collect all arguments for the java command, following the shell quoting conventions.
+#
+# (Note that we must follow the quoting conventions of the _current_ shell, not
+# necessarily the one that the user is running. For example, if the user is
+# running dash, we must still generate a command that is valid for whatever
+# shell is located at /bin/sh.)
+#
+# We set CLASSPATH here; if we set it as an environment variable, it's
+# length can exceed the maximum command line length.
+eval set -- "$JAVA_EXE" "$DEFAULT_JVM_OPTS" "$JAVA_OPTS" "$GRADLE_OPTS" "$ADDITIONAL_OPTS" -classpath "\"$APP_HOME/gradle/wrapper/gradle-wrapper.jar\"" org.gradle.wrapper.GradleWrapperMain '"$@"'
+
+# Execute the command, printing it first.
+# (We're careful to use printf for the command printing, to avoid any issues
+# with echo's parsing of options.)
+printf "Executing command:\n"
+printf "%q " "$@"
+printf "\n\n"
+exec "$@"
